### PR TITLE
fixing error in line 36

### PR DESCRIPTION
**Pull request by sair770**
File in Templates is Insane.py but while it is being opened with different probably old name

### CODE REVIEW

**Comment by 4w4k3** [comment]
If you has changed this, encrypt code func dont work anymore. Do you have try it?

**Comment by sair770** [comment]
Ok I will try but by not changing the name we cannot access the file

**Comment by 4w4k3** [comment]
Whats your OS?

**Comment by Ekultek** [comment]
Is there a reason this hasn't been merged?

**Comment by Ekultek** [comment]
If you look at templates, the name is clearly `insane.py`. However on line 36 in `dammed.py` you are opening `insane_enc.py` in read only mode, therefore not only does the file not exist, it isn't being created either. So python will throw an error, and the application will crash.

**Comment by 4w4k3** [comment]
Insanity don't work fine in your machines?

**Comment by 4w4k3** [comment]
When start enc.py, he create insane_enc.

**Comment by 4w4k3** [comment]
Ekultek do you can help me to fix this errors? On my system, are working 100% fine.

**Comment by Ekultek** [comment]
I just opened a pull request for what I think he was trying to accomplish Test it for me

**Comment by Ekultek** [comment]
I think what is happening is they aren't running enc first so it's failing. You should write a configuration for it, close this and I'll open an issue for an enhancement

**Pull request closed without merging**
